name: Rebuild Site

# This workflow is triggered by the webhook or can be manually dispatched
on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Specific directory to rebuild'
        required: false
        default: ''
      tableName:
        description: 'Table that was updated'
        required: false
        default: ''
      recordId:
        description: 'ID of the record that was updated'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Log rebuild trigger details
        run: |
          echo "Rebuilding site"
          echo "Directory: ${{ github.event.inputs.directory || 'all' }}"
          echo "Table: ${{ github.event.inputs.tableName || 'not specified' }}"
          echo "Record ID: ${{ github.event.inputs.recordId || 'not specified' }}"
      
      - name: Build site
        run: npm run build
        env:
          NOCODB_API_URL: ${{ secrets.NOCODB_API_URL }}
          NOCODB_AUTH_TOKEN: ${{ secrets.NOCODB_AUTH_TOKEN }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          # Add any other required environment variables
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          
      # Alternative: Deploy to Netlify
      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2
      #   with:
      #     publish-dir: './dist'
      #     production-branch: main
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #     enable-pull-request-comment: false
      #     enable-commit-comment: false
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}