name: Selective Rebuild on Content Change

on:
  repository_dispatch:
    types: [content-update]

jobs:
  selective-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Log build information
        run: |
          echo "Triggered by content update in directory: ${{ github.event.client_payload.directory }}"
          echo "Operation: ${{ github.event.client_payload.operation }}"
          echo "Table: ${{ github.event.client_payload.table }}"
        
      - name: Selective build
        run: node scripts/selective-build.js ${{ github.event.client_payload.directory }}
        env:
          NOCODB_API_URL: ${{ secrets.NOCODB_API_URL }}
          NOCODB_AUTH_TOKEN: ${{ secrets.NOCODB_AUTH_TOKEN }}
      
      # For GitHub Pages deployment
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
          
      # For AWS S3 deployment (uncomment if using S3)
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      
      # - name: Deploy to S3
      #   run: |
      #     if [ "${{ github.event.client_payload.directory }}" != "all" ]; then
      #       aws s3 sync dist/${{ github.event.client_payload.directory }} s3://${{ github.event.client_payload.directory }}-bucket/ --delete
      #     else
      #       for dir in dist/*; do
      #         if [ -d "$dir" ]; then
      #           dirname=$(basename $dir)
      #           aws s3 sync $dir s3://$dirname-bucket/ --delete
      #         fi
      #       done
      #     fi